---
label: project
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
- name: sub_heading
  label: Sub Heading
  type: text
  hidden: false
  default: ''
- name: banner_image
  label: Banner Image
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- type: number
  name: aaa
  label: AAA
  description: An aaa
  config:
    min: '1'
    max: '5'
    step: '1'
    required: false
